title: Siti Web fvg
email: info@sitiweb.fvg.it
tel: +39-388-9005888
description: Siti Web fvg, websites design, a Udine a Trieste e in tutto il Friuli. Siti web per aziende, siti internet per liberi professionisti , siti responsive e mobile.
baseurl: "/"
url: "http://www.sitiweb.fvg.it"
facebook_username: SITIWEB.fvg
linkedin_username: SITIWEB.fvg

# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Siti Web fvg | Agenzia  Web Udine
  email: "info@sitiweb.fvg.it"
  facebook: sitiweb.fvg

#disqus: ""
disqus: "sitiweb.fvg"

# Build settings
markdown: kramdown

permalink: /:month-:day-:year/:title.html
